version: "3.8"

services:
  db:
    image: verbetskyi/notes-db:latest
    container_name: notes_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    image: verbetskyi/notes-app:latest
    container_name: notes_app
    command: ["npm", "run", "dev"]
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    working_dir: /usr/src/app
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  pgdata:
